CREATE TABLE PARENTS
( ID                                        NUMBER(19)                GENERATED BY DEFAULT AS IDENTITY
, NAME                                      VARCHAR2(100 CHAR)        NOT NULL
, CREATED                                   TIMESTAMP(6)              NOT NULL
, MODIFIED                                  TIMESTAMP(6)
, CONSTRAINT PARENTS_PK                     PRIMARY KEY (ID)
);

CREATE TABLE CHILDREN
( ID                                        NUMBER(19)                GENERATED BY DEFAULT AS IDENTITY
, NAME                                      VARCHAR2(100 CHAR)        NOT NULL
, PARENT_ID                                 NUMBER(19)                NOT NULL
, CREATED                                   TIMESTAMP(6)              NOT NULL
, MODIFIED                                  TIMESTAMP(6)
, CONSTRAINT CHILDREN_PK                    PRIMARY KEY (ID)
, CONSTRAINT PARENTS_ID_FK                  FOREIGN KEY (PARENT_ID)   REFERENCES PARENTS (ID)
);
